### ISSUE TITLE
Consulta por el ejercicio 3.1

### ISSUE THREAD

**Issue by FriendlyFiubense** [NicolasEzequielZulaicaRivera/FIUBS_ANINFO#1]
Buenas! 

Estaba intentando resolver el ejercicio 3.1 y sinceramente tengo varias consultas con respecto a la resolución. No he podido llegar a un acuerdo con mis compañeros de cursada con respecto a una posible solución para varios de los casos y queríamos saber si tenías los resultados de esta entrega en particular.

Consulto porque veo que tenes información de los ejercicios de las clases 4 y 10.

Muchas gracias :)

**Comment by n-zu** [comment]
Buenas!

Hay mas ejercicios en el drive: [link](https://drive.google.com/drive/folders/1HPJoob3NpidMaohkA2y9bJiYzC276m_b?usp=sharing)

Saludos.
